### ISSUE TITLE
Unknown `NullPointerDereference` error caused by `store`

### ISSUE THREAD

**Issue by Just1ceP4rtn3r** [PLSysSec/haybale#20]
Hi, when I use Haybale to analyze some LLVM IR like:
```
store i8 0, i8* %376, align 1, !dbg !36589, !tbaa !9667
```
I step over the `strlen` function call because `strlen` is an unnecessary function in my project.  Then `%376` has the value: `(bvadd (bvadd BTOR_57@@handle__publish_name_strlen_retval_0 BTOR_57@@handle__publish_name_strlen_retval_1) #x0000000010144139)`. I think it's a symbolic value.
I have no idea why Haybale will throw a `NullPointerDereference` error. And How can I avoid this without stepping into `strlen` or closing the null pointer check of Haybale?

By the way, if set `null_pointer_checking` of config to `None`, haybale will write to the address that may be `NULL` anyway. And I found that this operation will modify the value in memory(`simple memory` indexed by BV). Is that a bug of haybale or we just can not store some value to a symbolic address?

**Comment by cdisselkoen** [comment]
Storing to symbolic address is supported, but will in many cases lead to very poor performance (long solver queries), as it is very difficult for the solver to reason about.  If possible, it's preferable to constrain the inputs so that there are as few stores to symbolic addresses as possible.

> I have no idea why Haybale will throw a `NullPointerDereference` error.

If a pointer value is completely unconstrained, and you're adding a constant (in this case `#x0000000010144139`), one of the possible values of the pointer is the value that causes the addition to result in exactly 0, hence a possible null pointer dereference.  To avoid this, you'd want to constrain the pointer value somehow, or constrain the inputs that lead to computing the pointer value.

For `strlen` specifically, you could consider providing a hook that returns some constrained value instead of an unconstrained value.  It depends on exactly what behavior you want to analyze.

**Comment by Just1ceP4rtn3r** [comment]
Thanks for answering my doubts!
